clean the in_patient and out_patient

In [1]:
import pandas as pd
import os

In [2]:
pm_oi = pd.read_csv(r"../Cleaned amr data\Sex_Clean.csv")

In [5]:
#inpsect the data
pm_oi['Location type'].value_counts(dropna=False)

Location type
in_patient     3086
out_patient    2641
NaN               1
mix               1
Name: count, dtype: int64

In [6]:
pm_oi.loc[
    pm_oi['Location type'] == 'mix',
    [
        'Identification number',
        'Hospital Name',
        'Ward',
        'Department',
        'Specimen type',
        'Location type'
    ]
]

,Identification number,Hospital Name,Ward,Department,Specimen type,Location type
971,182295,KCMC,Staff,cli,Urine,mix

since the ward is clinic means is mostly to be out_patient

In [7]:
#Standardize the 'mix' 
pm_oi['Location type'] = pm_oi['Location type'].replace('mix', 'out_patient')

In [9]:
#verify the changes
pm_oi.loc[
    pm_oi['Location type'] == 'mix',
    [
        'Identification number',
        'Hospital Name',
        'Ward',
        'Department',
        'Specimen type',
        'Location type'
    ]
]

Empty DataFrame
Columns: [Identification number, Hospital Name, Ward, Department, Specimen type, Location type]
Index: []

In [10]:
pm_oi['Location type'].value_counts(dropna=False)

Location type
in_patient     3086
out_patient    2642
NaN               1
Name: count, dtype: int64

fill nan with mode since no other clue from other columns

In [11]:
pm_oi['Location type'].mode()

0    in_patient
Name: Location type, dtype: str

In [13]:
#fill nan with mode
pm_oi['Location type'] = pm_oi['Location type'].fillna(
    pm_oi['Location type'].mode()[0])

In [16]:
#verify the changes
pm_oi['Location type'].value_counts(dropna=False)

Location type
in_patient     3087
out_patient    2642
Name: count, dtype: int64

In [ ]:
#save the cleaned data
#pm_oi.to_csv(r"../Cleaned amr data\LocationType_Clean.csv", index=False)

In [19]:
pm_oi['Department'].value_counts(dropna=False)

Department
med     1718
ped      716
out      565
mix      515
sur      432
obg      343
eme      255
neo      215
MED      180
nicu     156
hao      126
icu      122
cli      113
oth       86
uro       64
anc       30
uc        18
OTH       16
int       11
PED       10
EME        9
psy        7
burn       4
OBG        3
mal        3
gs         2
ot         2
HAO        2
SUR        2
NaN        1
CLI        1
card       1
meta       1
Name: count, dtype: int64